// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:main.Person):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectFile():Promise<string>;
